# -*- coding: utf-8 -*-
"""EfficientNetB0 + Logistic Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRb36E_n3-t0Psl_dhVG8IROBiaBfb7I
"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!mkdir -p /kaggle/working/mangoleaf
!kaggle datasets download -d tahmidmir/mangoleaf -p /kaggle/working/mangoleaf --unzip
!ls -R /kaggle/working/mangoleaf | head -n 40

import os
DATASET_PATH = "/kaggle/working/mangoleaf/MangoLeafBD"
TRAIN_DIR = os.path.join(DATASET_PATH, "Train")
VAL_DIR = os.path.join(DATASET_PATH, "Test")
print("Train Directory:", TRAIN_DIR)
print("Validation Directory:", VAL_DIR)

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from torchvision import models, transforms
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report, accuracy_score, precision_score,
    recall_score, f1_score, matthews_corrcoef, confusion_matrix, ConfusionMatrixDisplay
)
from tqdm import tqdm
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

data_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.3),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
])

def vegetation_mask(image):
    hsv = image.convert("HSV")
    h, s, v = hsv.split()
    h = np.array(h)
    s = np.array(s)
    mask = (h > 25) & (h < 100) & (s > 40)
    mask = Image.fromarray((mask * 255).astype(np.uint8))
    return mask

class MangoLeafDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.paths, self.labels = [], []
        self.transform = transform
        for label, cls in enumerate(sorted(os.listdir(root_dir))):
            folder = os.path.join(root_dir, cls)
            for img_name in os.listdir(folder):
                self.paths.append(os.path.join(folder, img_name))
                self.labels.append(label)
    def __len__(self):
        return len(self.paths)
    def __getitem__(self, idx):
        img = Image.open(self.paths[idx]).convert("RGB")
        mask = vegetation_mask(img)
        img = Image.composite(img, Image.new("RGB", img.size, (0, 0, 0)), mask)
        if self.transform:
            img = self.transform(img)
        return img, self.labels[idx]

class FeatureExtractor(nn.Module):
    def __init__(self):
        super().__init__()
        self.resnet = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V2)
        self.efficient = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.IMAGENET1K_V1)
        self.resnet = nn.Sequential(*(list(self.resnet.children())[:-1]))
        self.efficient = nn.Sequential(*(list(self.efficient.children())[:-1]))
        for model in [self.resnet, self.efficient]:
            for param in model.parameters():
                param.requires_grad = False
    def forward(self, x):
        r = self.resnet(x)
        e = self.efficient(x)
        r = r.view(r.size(0), -1)
        e = torch.mean(e, dim=(2, 3))
        return torch.cat((r, e), dim=1)

def extract_features(model, dataloader, device):
    model.eval()
    all_feats, all_labels = [], []
    with torch.no_grad():
        for imgs, labels in tqdm(dataloader):
            imgs = imgs.to(device)
            feats = model(imgs)
            all_feats.append(feats.cpu().numpy())
            all_labels.append(labels.numpy())
    return np.vstack(all_feats), np.hstack(all_labels)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
train_dataset = MangoLeafDataset(TRAIN_DIR, transform=data_transforms)
val_dataset = MangoLeafDataset(VAL_DIR, transform=data_transforms)
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False)

feature_model = FeatureExtractor().to(device)
print("Extracting features from training set...")
X_train, y_train = extract_features(feature_model, train_loader, device)
print("Extracting features from validation set...")
X_val, y_val = extract_features(feature_model, val_loader, device)

X_train = X_train + np.random.normal(0, 0.25, X_train.shape)
X_val = X_val + np.random.normal(0, 0.25, X_val.shape)

clf = LogisticRegression(max_iter=60, C=0.001, solver='lbfgs')
clf.fit(X_train, y_train)
preds = clf.predict(X_val)

acc = accuracy_score(y_val, preds)
prec = precision_score(y_val, preds, average='macro')
rec = recall_score(y_val, preds, average='macro')
f1 = f1_score(y_val, preds, average='macro')
mcc = matthews_corrcoef(y_val, preds)

print(f"\nAccuracy: {acc*100:.2f}%")
print(f"Precision: {prec*100:.2f}%")
print(f"Recall: {rec*100:.2f}%")
print(f"F1 Score: {f1*100:.2f}%")
print(f"MCC: {mcc:.4f}")

cm = confusion_matrix(y_val, preds)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap="Blues", xticks_rotation=45)
plt.show()

print("\nClassification Report:\n", classification_report(y_val, preds))